//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./demo_types');
//HELPER FUNCTIONS AND STRUCTURES

var Demo_rpcCall_args = function(args) {
  this.jsonarg = null;
  if (args) {
    if (args.jsonarg !== undefined && args.jsonarg !== null) {
      this.jsonarg = args.jsonarg;
    }
  }
};
Demo_rpcCall_args.prototype = {};
Demo_rpcCall_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.jsonarg = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Demo_rpcCall_args.prototype.write = function(output) {
  output.writeStructBegin('Demo_rpcCall_args');
  if (this.jsonarg !== null && this.jsonarg !== undefined) {
    output.writeFieldBegin('jsonarg', Thrift.Type.STRING, 1);
    output.writeString(this.jsonarg);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Demo_rpcCall_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
Demo_rpcCall_result.prototype = {};
Demo_rpcCall_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Demo_rpcCall_result.prototype.write = function(output) {
  output.writeStructBegin('Demo_rpcCall_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var DemoClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
DemoClient.prototype = {};
DemoClient.prototype.seqid = function() { return this._seqid; };
DemoClient.prototype.new_seqid = function() { return this._seqid += 1; };
DemoClient.prototype.rpcCall = function(jsonarg, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_rpcCall(jsonarg);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_rpcCall(jsonarg);
  }
};

DemoClient.prototype.send_rpcCall = function(jsonarg) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('rpcCall', Thrift.MessageType.CALL, this.seqid());
  var params = {
    jsonarg: jsonarg
  };
  var args = new Demo_rpcCall_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

DemoClient.prototype.recv_rpcCall = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Demo_rpcCall_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('rpcCall failed: unknown result');
};
var DemoProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
DemoProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
DemoProcessor.prototype.process_rpcCall = function(seqid, input, output) {
  var args = new Demo_rpcCall_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.rpcCall.length === 1) {
    Q.fcall(this._handler.rpcCall.bind(this._handler), args.jsonarg)
      .then(function(result) {
        var result_obj = new Demo_rpcCall_result({success: result});
        output.writeMessageBegin("rpcCall", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("rpcCall", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.rpcCall(args.jsonarg, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new Demo_rpcCall_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("rpcCall", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("rpcCall", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
